# Generated by Django 5.2.1 on 2025-05-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='image',
            field=models.ImageField(null=True, upload_to='merchandise/'),
        ),
    ]
