# Generated by Django 5.2.1 on 2025-05-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_merchandise_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='description',
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='merchandise/'),
        ),
    ]
