# Generated by Django 5.2.1 on 2025-05-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_merchandise_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/merchandise/'),
        ),
    ]
