# Generated by Django 5.2.1 on 2025-05-12 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_merchandise_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('phone_number', models.CharField(max_length=8)),
                ('merchandise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.merchandise')),
            ],
        ),
    ]
